package rules;

import com.sunjinwei.entity.Order

// 规则1 100元以下 不积分
rule "score_1"
when
    $order:Order(amount<100)
then
    $order.setScore(0);
    System.out.println("触发了规则1：100以下 不积分");
end

// 规则2 100-500 加100积分
rule "score_2"
when
    $order:Order(amount>=100&&amount<=500)
then
    $order.setScore(100);
    System.out.println("触发了规则2：100-500 加100积分");
end

// 规则3 500-1000 加500分
rule "score_3"
when
    $order:Order(amount>500&&amount<=1000)
then
    $order.setScore(0);
    System.out.println("触发了规则3：500-1000 加500积分");
end

// 规则4 1000以上 加1000积分
rule "score_4"
when
    $order:Order(amount>1000)
then
    $order.setScore(0);
    System.out.println("触发了规则4： 1000以上 加1000积分");
end