package rules

import com.sunjinwei.springboot.model.Violation
import com.sunjinwei.springboot.model.TrafficViolation
import com.sunjinwei.springboot.model.Fine

rule "rule_01"
    when
        trafficViolation: TrafficViolation(violation != null && driver != null)
        violation: Violation(type == "speed" && actualSpeed < 100)
        fine: Fine()
    then
        fine.setPoints(0);
        fine.setAmount(0);
        trafficViolation.setFine(fine);
        trafficViolation.setSuspended("NO");
end

rule "rule_02"
    when
        trafficViolation: TrafficViolation(violation != null && driver != null)
        violation: Violation(type == "speed" && actualSpeed > 100 && actualSpeed < 150)
        fine: Fine()
    then
        fine.setPoints(3);
        fine.setAmount(500);
        trafficViolation.setFine(fine);
        trafficViolation.setSuspended("NO");
end

rule "rule_03"
    when
        trafficViolation: TrafficViolation(violation != null && driver != null)
        violation: Violation(type == "speed" && actualSpeed > 150)
        fine: Fine()
    then
        fine.setPoints(5);
        fine.setAmount(1000);
        trafficViolation.setFine(fine);
        trafficViolation.setSuspended("YES");
end

