package rules

import com.sunjinwei.springboot.model.Violation
import com.sunjinwei.springboot.model.TrafficViolation
import com.sunjinwei.springboot.model.Fine


rule "rule_01"
    when
        trafficViolation: TrafficViolation(violation != null && driver != null)
        violation: Violation(type == "speed" && actualSpeed > 100 && actualSpeed < 200)
        fine: Fine()
    then
        fine.setPoints(3);
        fine.setAmount(500);
        trafficViolation.setFine(fine);
        trafficViolation.setSuspended("NO");
		System.out.println("规则中打印日志：校验通过!");
end